# Exemplo: Conjunto holdout
----------------------

Este exemplo mostra quando e como usar o conjunto holdout do ExperionML em um pipeline de exploração.

Os dados utilizados são uma variação do [conjunto de dados de clima australiano](https://www.kaggle.com/jsphyg/weather-dataset-rattle-package) do Kaggle. Você pode baixá-lo [aqui](https://github.com/tvdboom/ExperionML/blob/master/examples/datasets/weatherAUS.csv). O objetivo deste conjunto é prever se vai chover amanhã treinando um classificador binário com a variável alvo `RainTomorrow`.

## Carregar os dados

In [1]:
# Import packages
import pandas as pd
from experionml import ExperionMLClassifier

In [2]:
# Carregue os dados
X = pd.read_csv("./datasets/weatherAUS.csv")

# Let's have a look
X.head()

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,MelbourneAirport,18.0,26.9,21.4,7.0,8.9,SSE,41.0,W,SSE,...,95.0,54.0,1019.5,1017.0,8.0,5.0,18.5,26.0,Yes,0
1,Adelaide,17.2,23.4,0.0,NaN,NaN,S,41.0,S,WSW,...,59.0,36.0,1015.7,1015.7,NaN,NaN,17.7,21.9,No,0
2,Cairns,18.6,24.6,7.4,3.0,6.1,SSE,54.0,SSE,SE,...,78.0,57.0,1018.7,1016.6,3.0,3.0,20.8,24.1,Yes,0
3,Portland,13.6,16.8,4.2,1.2,0.0,ESE,39.0,ESE,ESE,...,76.0,74.0,1021.4,1020.5,7.0,8.0,15.6,16.0,Yes,1
4,Walpole,16.4,19.9,0.0,NaN,NaN,SE,44.0,SE,SE,...,78.0,70.0,1019.4,1018.9,NaN,NaN,17.4,18.1,No,0

## Executar o pipeline

In [3]:
# Inicialize o experionml especificando uma fração do conjunto de dados para holdout
experionml = ExperionMLClassifier(X, n_rows=0.5, holdout_size=0.2, verbose=2)

<< ================== ExperionML ================== >>

Configuração ==================== >>
Tarefa do algoritmo: Binary classification.

Estatísticas do conjunto de dados ==================== >>
Formato: (56877, 22)
Tamanho do conjunto de train: 42658
Tamanho do conjunto de test: 14219
Tamanho do conjunto de holdout: 14219
-------------------------------------
Memória: 10.01 MB

Escalonado: False
Valores ausentes: 126667 (10.1%)
Atributos categóricos: 5 (23.8%)
Duplicatas: 20 (0.0%)

In [4]:
# As frações de teste e holdout são separadas após a subamostragem do conjunto de dados
# Observe também que o conjunto holdout não faz parte do dataset do experionml
print("Length loaded data:", len(X))
print("Tamanho dataset + holdout:", len(experionml.dataset) + len(experionml.holdout))

Length loaded data: 142193
Tamanho dataset + holdout: 71096

In [5]:
experionml.impute()
experionml.encode()

Ajustando Imputer...
Imputando valores ausentes...

 --> Imputando 243 valores ausentes com mean (12.21) na coluna MinTemp.
 --> Imputando 120 valores ausentes com mean (23.22) na coluna MaxTemp.
 --> Imputando 566 valores ausentes com mean (2.31) na coluna Rainfall.
 --> Imputando 24284 valores ausentes com mean (5.47) na coluna Evaporation.
 --> Imputando 27107 valores ausentes com mean (7.61) na coluna Sunshine.
 --> Imputando 3704 valores ausentes com most_frequent (W) na coluna WindGustDir.
 --> Imputando 3682 valores ausentes com mean (39.93) na coluna WindGustSpeed.
 --> Imputando 3968 valores ausentes com most_frequent (N) na coluna WindDir9am.
 --> Imputando 1498 valores ausentes com most_frequent (SE) na coluna WindDir3pm.
 --> Imputando 547 valores ausentes com mean (14.0) na coluna WindSpeed9am.
 --> Imputando 1041 valores ausentes com mean (18.64) na coluna WindSpeed3pm.
 --> Imputando 716 valores ausentes com mean (68.78) na coluna Humidity9am.
 --> Imputando 1451 valores ausentes com mean (51.54) na coluna Humidity3pm.
 --> Imputando 5651 valores ausentes com mean (1017.68) na coluna Pressure9am.
 --> Imputando 5634 valores ausentes com mean (1015.28) na coluna Pressure3pm.
 --> Imputando 21495 valores ausentes com mean (4.44) na coluna Cloud9am.
 --> Imputando 22904 valores ausentes com mean (4.5) na coluna Cloud3pm.
 --> Imputando 388 valores ausentes com mean (17.0) na coluna Temp9am.
 --> Imputando 1102 valores ausentes com mean (21.69) na coluna Temp3pm.
 --> Imputando 566 valores ausentes com most_frequent (No) na coluna RainToday.
Ajustando Encoder...

Codificando colunas categóricas...
 --> Aplicando Target-encoding à variável Location. Ela contém 49 classes.
 --> Aplicando Target-encoding à variável WindGustDir. Ela contém 16 classes.
 --> Aplicando Target-encoding à variável WindDir9am. Ela contém 16 classes.
 --> Aplicando Target-encoding à variável WindDir3pm. Ela contém 16 classes.
 --> Aplicando Ordinal-encoding à variável RainToday. Ela contém 2 classes.

In [6]:
# Diferentemente de treino e teste, o conjunto holdout não é transformado até ser usado para predições
experionml.holdout

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
56877,Sale,7.7,19.5,0.2,NaN,NaN,E,33.0,WNW,E,...,81.0,60.0,1022.2,1021.3,1.0,8.0,11.3,19.3,No,0
56878,Canberra,14.7,34.2,0.0,6.6,12.8,NE,33.0,WNW,NW,...,64.0,25.0,1017.8,1013.3,1.0,1.0,21.3,32.2,No,0
56879,Williamtown,12.6,25.8,NaN,NaN,NaN,NW,39.0,NW,NNW,...,68.0,59.0,1014.3,1012.5,NaN,8.0,20.0,21.3,NaN,0
56880,Penrith,8.1,22.8,0.0,NaN,NaN,ESE,28.0,ENE,SSE,...,45.0,32.0,NaN,NaN,NaN,NaN,16.9,22.2,No,0
56881,Moree,5.9,29.3,0.0,6.0,11.2,NE,24.0,NNE,SW,...,33.0,13.0,1014.0,1009.6,0.0,0.0,18.6,28.2,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71091,SalmonGums,7.4,26.1,0.0,NaN,NaN,N,28.0,N,ESE,...,66.0,40.0,NaN,NaN,NaN,NaN,19.1,24.2,No,0
71092,Launceston,12.6,23.0,0.0,NaN,NaN,NNW,48.0,NNW,NNW,...,76.0,59.0,1007.3,1003.2,NaN,NaN,17.5,21.8,No,0
71093,PearceRAAF,21.9,29.6,29.8,NaN,0.7,ENE,35.0,SE,WSW,...,88.0,78.0,1015.9,1015.4,7.0,8.0,24.0,26.2,Yes,0
71094,Newcastle,5.2,18.2,0.2,NaN,NaN,NaN,NaN,NaN,SE,...,97.0,68.0,NaN,NaN,6.0,6.0,9.4,16.2,No,0
71095,Nhil,9.5,22.0,0.0,NaN,NaN,WNW,39.0,NNW,WNW,...,86.0,54.0,1022.2,1020.0,NaN,NaN,12.5,21.5,No,0

In [7]:
experionml.run(models=["GNB", "LR", "RF"])

Training ========================= >>
Models: GNB, LR, RF
Metric: f1


Results for GaussianNB:
Fit ---------------------------------------------

Train evaluation --> f1: 0.5788
Test evaluation --> f1: 0.5775
Time elapsed: 0.351s
-------------------------------------------------
Time: 0.351s

Results for LogisticRegression:
Fit ---------------------------------------------

Train evaluation --> f1: 0.5728

Test evaluation --> f1: 0.5754
Time elapsed: 1.573s

-------------------------------------------------
Time: 1.573s


Results for RandomForest:
Fit ---------------------------------------------

Train evaluation --> f1: 0.9999

Test evaluation --> f1: 0.6016
Time elapsed: 9.509s

-------------------------------------------------
Time: 9.509s


Resultados finais ==================== >>
Tempo total: 12.280s
-------------------------------------

GaussianNB         --> f1: 0.5775

LogisticRegression --> f1: 0.5754
RandomForest       --> f1: 0.6016 ~ !

In [8]:
experionml.plot_prc()

In [9]:
# Com base nos resultados no conjunto de teste, selecionamos o melhor modelo para ajuste adicional
experionml.run("lr_tuned", n_trials=10)

Training ========================= >>
Models: LR_tuned
Metric: f1


Running hyperparameter tuning for LogisticRegression...
| trial | penalty |       C |  solver | max_iter | l1_ratio |      f1 | best_f1 | time_trial | time_ht |    state |
| ----- | ------- | ------- | ------- | -------- | -------- | ------- | ------- | ---------- | ------- | -------- |

| 0     |    None | 10.9349 |   lbfgs |      370 |      0.8 |  0.5745 |  0.5745 |     0.939s |  0.939s | COMPLETE |

| 1     |      l2 |  0.1081 |     sag |      900 |      0.6 |   0.567 |  0.5745 |     0.813s |  1.752s | COMPLETE |

| 2     |      l2 | 56.9607 |     sag |      980 |      0.1 |  0.5716 |  0.5745 |     0.809s |  2.562s | COMPLETE |

| 3     |    None |  2.4091 |   lbfgs |      610 |      0.4 |  0.5773 |  0.5773 |     1.343s |  3.905s | COMPLETE |

| 4     |      l2 |  0.0037 |     sag |      690 |      0.8 |  0.5507 |  0.5773 |     0.821s |  4.725s | COMPLETE |

| 5     |      l2 |  0.1053 | newto.. |      930 |      0.6 |  0.5706 |  0.5773 |     0.762s |  5.487s | COMPLETE |

| 6     |    None |  0.0111 | newto.. |      890 |      0.5 |  0.5761 |  0.5773 |     0.782s |  6.270s | COMPLETE |

| 7     |      l2 |  0.0161 |   lbfgs |      680 |      0.0 |  0.5637 |  0.5773 |     1.353s |  7.623s | COMPLETE |

| 8     |      l2 |  0.3998 | libli.. |      130 |      0.6 |   0.576 |  0.5773 |     0.937s |  8.560s | COMPLETE |

| 9     |      l2 |  4.7057 | libli.. |      540 |      0.6 |  0.5683 |  0.5773 |     0.757s |  9.318s | COMPLETE |
Hyperparameter tuning ---------------------------
Best trial --> 3
Best parameters:
 --> penalty: None
 --> C: 2.4091
 --> solver: lbfgs
 --> max_iter: 610
 --> l1_ratio: 0.4
Best evaluation --> f1: 0.5773
Time elapsed: 9.318s
Fit ---------------------------------------------

Train evaluation --> f1: 0.5728

Test evaluation --> f1: 0.5753
Time elapsed: 1.670s

-------------------------------------------------
Time: 10.987s


Resultados finais ==================== >>
Tempo total: 11.536s
-------------------------------------

LogisticRegression --> f1: 0.5753

## Analisar os resultados

Já usamos o conjunto de teste para escolher o melhor modelo para ajuste adicional, então esse conjunto deixou de ser verdadeiramente independente. Embora isso talvez não fique visível diretamente nos resultados, usar o conjunto de teste agora para avaliar o modelo LR ajustado seria um erro, pois ele já carrega viés. Por esse motivo, separamos um conjunto extra e independente para validar o modelo final: o holdout. Se não vamos usar o conjunto de teste para validação, também podemos aproveitá-lo para treinar o modelo e otimizar o uso dos dados disponíveis. Use o método full_train para isso.

In [10]:
# Retreine o modelo no conjunto completo, treino + teste 
experionml.lr_tuned.full_train()

Fit ---------------------------------------------

Train evaluation --> f1: 0.5737

Test evaluation --> f1: 0.5757
Time elapsed: 3.138s

In [11]:
# Avalie no conjunto holdout
experionml.lr_tuned.evaluate(rows="holdout")

accuracy     0.8460
ap           0.6949
ba           0.7192
f1           0.5868
jaccard      0.4152
mcc          0.5114
precision    0.7300
recall       0.4905
auc          0.8702
Name: LR_tuned, dtype: float64

In [12]:
experionml.lr_tuned.plot_prc(rows="holdout", legend="upper right")